### ISSUE TITLE
Add support for Crawl-Delay

### ISSUE THREAD

**Issue by mikefaraponov** [temoto/robotstxt#22]
Just a feature request

**Comment by temoto** [comment]
Do you mean add documentation or existing support doesn't work as expected?

**Comment by mikefaraponov** [comment]
I mean support to extract crawl delay from robotstxt

**Comment by mikefaraponov** [comment]
forgot what I say

**Comment by mikefaraponov** [comment]
How about providing support for extended format
Request-rate: 1/5        
Visit-time: 0600-0845

**Comment by temoto** [comment]
Yes, of course, will add those, if nobody beats me to it. (wink wink)

Does your crawler use request rate?

**Comment by moredure** [comment]
Yes, my crawler using mercator scheme and doing pauses Nth times of request duration of course no more than some smart amount of time.
